apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tegola.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tegola.name" . }}
    helm.sh/chart: {{ include "tegola.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.toml: |-
{{ .Values.config | indent 4 }}